name: Build and publish

on:
  push:
    branches:
      - main
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.TOKEN_NPM}}" >> ~/.npmrc
      - run: echo "@verybigthings:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: npm i
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_NPM}}
        continue-on-error: true
